import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router";
import Form from 'react-bootstrap/Form';
import "bootstrap/dist/css/bootstrap.min.css";

export default function Ajout() {

  const router = useRouter();
  const [nom, setNom] = useState("");

  const submit = async (e) => {
    e.preventDefault();
 //   console.log("nom", nom)
    try {
        await fetch('http://localhost:3000/ajoutthe', {
            method: 'POST',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              nom
            }),
        });

        await router.push('/');
    } catch (e) {
        console.log("erreur", e);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h3>Ajouter un professionnel</h3>
          <Form onSubmit={submit}>
              <Form.Group className="mb-3">
                  <Form.Label>Nom</Form.Label>
                  <Form.Control onChange={e => setNom(e.target.value)} />
              </Form.Group>
              
              <button className="btn btn-primary" variant="primary" type="submit">
                  Ajouter
              </button>
          </Form>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
